### ISSUE TITLE
Error showing 

### ISSUE THREAD

**Issue by bluegangsta78** [Pure-L0G1C/InstaBurst#10]
Can u pls help 
File "instagram.py", line 5, in <module>
    from lib.tor import tor_exists
  File "/data/data/com.termux/files/home/InstaBurst/lib/tor.py", line 6, in <module>
    from commands import getoutput as shell
ModuleNotFoundError: No module named 'commands'
$ python instagram.py
Traceback (most recent call last):
  File "instagram.py", line 5, in <module>
    from lib.tor import tor_exists
  File "/data/data/com.termux/files/home/InstaBurst/lib/tor.py", line 6, in <module>
    from commands import getoutput as shell
ModuleNotFoundError: No module named 'commands'

**Comment by Ethical-H4CK3R** [comment]
I wrote the program to run on Kali Linux not Android.

>

**Comment by bluegangsta78** [comment]
Oh sry..

**Comment by x1ox** [comment]
the brute works fine bu when I print help  i get this error


root> help 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 2403, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 2598, in onecmd
    stop = func(statement)
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 351, in cmd_wrapper
    func(self, lexed_arglist)
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 2901, in do_help
    self._help_menu()
  File "/root/instagram/InstaBurst/lib/console.py", line 52, in _help_menu
    for name in self.exclude_from_help:
AttributeError: 'Instagram' object has no attribute 'exclude_from_help'
EXCEPTION of type 'AttributeError' occurred with message: ''Instagram' object has no attribute 'exclude_from_help''
To enable full traceback, run the following command:  'set debug true'
root>

**Comment by Prabha10cs** [comment]
@Pure-L0G1C 
you have windows besed code

**Comment by Pure-L0G1C** [comment]
No, just use the other program
