### ISSUE TITLE
command help doesn't work

### ISSUE THREAD

**Issue by R3nt0n** [Pure-L0G1C/InstaBurst#16]
Awesome tool, bro!

The only issue i found was when I tried to list all the commands with `help`:

```
root> help
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 2396, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 2591, in onecmd
    stop = func(statement)
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 383, in cmd_wrapper
    return func(self, lexed_arglist)
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 2873, in do_help
    self._help_menu(verbose)
TypeError: _help_menu() takes exactly 1 argument (2 given)
EXCEPTION of type 'TypeError' occurred with message: '_help_menu() takes exactly 1 argument (2 given)'
To enable full traceback, run the following command:  'set debug true'
```

**Comment by Pure-L0G1C** [comment]
It should be working now.
