### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by rahulmanek** [Pure-L0G1C/InstaBurst#3]
No protocol specified
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
/usr/local/lib/python2.7/dist-packages/pyperclip/__init__.py:143: GtkWarning: IA__gtk_clipboard_get_for_display: assertion 'display != NULL' failed
  clipboardContents = gtk.Clipboard().wait_for_text()
Traceback (most recent call last):
  File "instagram.py", line 6, in <module>
    from lib.console import Console
  File "/home/user/InstaBurst/lib/console.py", line 6, in <module>
    from cmd2 import Cmd
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 670, in <module>
    _ = pyperclip.paste()
  File "/usr/local/lib/python2.7/dist-packages/pyperclip/__init__.py", line 596, in lazy_load_stub_paste
    return paste()
  File "/usr/local/lib/python2.7/dist-packages/pyperclip/__init__.py", line 143, in paste_gtk
    clipboardContents = gtk.Clipboard().wait_for_text()
RuntimeError: could not create GtkClipboard object

**Comment by Ethical-H4CK3R** [comment]
did you run the install script?

**Comment by rahulmanek** [comment]
Yes

**Comment by x1ox** [comment]
what i missed ! ..
root> help

		Possible Commands (type help <command>)
+-------------------------------------------------------------------------+
capture_list     database    monitor   remove   start_phish
change_username  delete      queue     reset    stop       
change_wordlist  exit        quit      restart  stop_phish 
create           get_banner  recreate  start  

root> capture_list
root> start_phish

	[+] Starting social engineering attack ...


	[!] Error: Phishing attack failed, try again in a while!

**Comment by bluegangsta78** [comment]
I am getting this error , can anybody help
Traceback (most recent call last):
  File "instagram.py", line 5, in <module>
    from lib.tor import tor_exists
  File "/data/data/com.termux/files/home/InstaBurst/lib/tor.py", line 6, in <module>
    from commands import getoutput as shell
ModuleNotFoundError: No module named 'commands'

**Comment by Ethical-H4CK3R** [comment]
This program is meant to run on Kali Linux
